### ISSUE TITLE
Implement Reversi UI

### ISSUE THREAD

**Issue by seungjoonH** [seungjoonH/reversi#2]
# Implement Reversi UI

## Description
* Create a user-interface for the Reversi game using the `ncurses` library.

## Task
* [x] Add the text Logo using ASCII art.
* [x] Set up the game board with an 8x8 grid.
* [x] Update the board display after each move.
* [x] Implement the ability to fill a cell when the space bar is pressed in that position.
* [x] Use different colors to fill the cells depending on the player.
