### ISSUE TITLE
Implement the formatted input for executing

### ISSUE THREAD

**Issue by seungjoonH** [seungjoonH/reversi#4]
# Implement the formatted input for executing

## Description
* Restrict the user input by preform syntax for program executing.

## Task
* [x] Restrict the server input to `./reversi -server [Port]`.
* [x] Restrict the client input to `./reversi -client [Ip addr] [Port]`.
* [x] All other inputs are rejected (terminates with error message).
