### ISSUE TITLE
Implement socket communication

### ISSUE THREAD

**Issue by seungjoonH** [seungjoonH/reversi#5]
# Implement socket communication

## Description
* Use socket communication ...
  * to allow each person to place their stone on the game board
  * to allow this information to be shared with each other in real time

## Task
* [x] Implement data transmission/reception between server and client.
* [x] Implement the features of encode/decode the data.
* [x] When one of the players puts his or her stone, the other can recognize it.
