### ISSUE TITLE
Fix bug on socket communication

### ISSUE THREAD

**Issue by seungjoonH** [seungjoonH/reversi#6]
# Fix bug on socket communication

## Description
* Fix several socket communication bugs while playing game.

## Task
* [x] Implement a mechanism where the player is not allowed to place another stone until the other player finishes the turn.
* [x] Implement a mechanism that prevents the player from placing stone where the stone already is.
* [x] Implement to display the cursor when it is the player's turn.
* [x] Implement to terminate the client program if the server is closed.
