### ISSUE TITLE
Implement Reversi game logic

### ISSUE THREAD

**Issue by saniolsida** [seungjoonH/reversi#7]
# Implement Reversi game logic

## Description
* Implement the logic of the Reversi game.

## Task
* [x] Mark the spot where a player can place the stone.
* [x] Flip the stones according to the rules of the Reversi game.
* [x] Implement the mechanism to pass turn to the opponent if there is no spot to place the stone.
* [x] Implement the end-of-game condition.
  * [x] Terminate the game if all spots are filled with stones.
  * [x] Terminate the game if one of the player has no more stones.
  * [x] Terminate the game if both players need to pass the turn to each other in a single turn.
